del Includes\raylib\utils.o
del Includes\raylib\utils.d
del Includes\raylib\rtextures.o
del Includes\raylib\rtextures.d
del Includes\imgui\imgui.o 
del Includes\imgui\imgui.d
del Includes\imgui\imgui_draw.o 
del Includes\imgui\imgui_draw.d 
del Includes\imgui\imgui_stdlib.o 
del Includes\imgui\imgui_stdlib.d 
del Includes\imgui\imgui_tables.o 
del Includes\imgui\imgui_tables.d 
del Includes\imgui\imgui_widgets.o 
del Includes\imgui\imgui_widgets.d 
del Includes\rlImGui\rlImGui.o 
del Includes\rlImGui\rlImGui.d
del Sources\FractalRenderer.o 
del Sources\FractalRenderer.d
del Sources\main.o 
del Sources\main.d
del Sources\Ui.o
del Sources\Ui.d
del Web\fractalExplorer.html
del Web\fractalExplorer.js
del Web\fractalExplorer.wasm
del Web\fractalExplorer.data